spring:
  elasticsearch:
    jest:
      uris: http://192.168.42.149:9200
      connection-timeout: 60000
  datasource:   #mysql数据库配置，使用DriverSpy驱动来捕捉发送到MySql的信息，输出查看查询语句
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password: curtis
    url: jdbc:log4jdbc:mysql://localhost:3360/bbs?useUnicode=yes&characterEncoding=UTF-8&useSSL=false #使用DriverSpy要更改url信息添加log4jdbc
  jpa:
    show-sql: false   #控制窗口不显示sql语句
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost #redis缓存本地服务器
    port: 6379      #redis端口
  mvc:
    static-path-pattern: /** #静态文件路径
    view:
      prefix: /
  devtools:
    restart:
      enabled: true #设计开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
debug: true
server:
  port: 8080
  servlet:
    context-path: /
icon:
  storage:
    forum:
      path: C:\Users\Curtis\IdeaProjects\bbs\src\main\resources\static\img\icon\
      url: http://localhost:8080/img/icon
ckeditor:
  storage:
    image:
      path: C:\Users\Curtis\IdeaProjects\bbs\src\main\resources\static\postimages\
  access:
    image:
      url: http://localhost:8080/postimages